name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: install
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: build
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: build
    - name: test
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: test
        
    
      
